import Header from '@/components/layout'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/views/Footer'
import Navbar from '@/components/layout'
import Wrapper from '@/components/shared/Wrapper'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by Hammad Jutt web of hackaton 2',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>


        <Navbar />
        <main className='px-8'>
          <div className='min-h-screen'>
            {children}
          </div>
          <Footer />

        </main>

      </body>
    </html >
  )
}
